# Generated by Django 3.2 on 2021-05-21 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0005_comment_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Post',
            new_name='post',
        ),
    ]
